### ISSUE TITLE
How to determine if project is up to date with theme

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#35]
I can look at a project's `go.mod` file such as [this one](https://github.com/LibraryCarpentry/lc-new-website/blob/main/go.mod) and I can figure out the updated date from that.  How can I then tell if this matches the most recent theme update? 

Along those lines, I am guessing the version 0.0 is named such since we are in testing.  We should be sure to use a clear versioning system.

**Comment by regisphilibert** [comment]
Version is 0.0.0 because we have no release on the theme for now. Once you create release on the theme's repo, `hugo mod get` will only update to latest release. See https://go.dev/doc/modules/version-numbers

I'd recommend remaining on a 0 version (0.1.0), because go has a strict policy on major version update: https://go.dev/doc/modules/major-version

**Comment by maneesha** [comment]
Completely understand you won't be maintaining releases under the scope of this project.  I wanted to see if there is a way to look at the theme and look at a project and tell from there if the project up to date with the theme.

**Comment by regisphilibert** [comment]
I think the hash in the version points to a commit, but you would have to confirm that. I'm not sure,

**Comment by maneesha** [comment]
Thanks.
